"""add bookmaker to value_bets, settled_bets and calibration_factors tables

Phase 10: `value_bets.bookmaker_id` (nullable FK - closes the
`ValueBet`-has-no-bookmaker gap flagged since Phase 6, needed to segment
calibration by bookmaker); new `settled_bets` table (denormalized copy of
a settled `ValueBet` plus its real-world result/CLV data, for
backtesting); new `calibration_factors` table (versioned correction
factors per segment, one new row per computation, never updated in
place).

Revision ID: d9433886bf4e
Revises: d4e1f9a2b613
Create Date: 2026-07-06 10:13:30.798633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9433886bf4e'
down_revision: Union[str, Sequence[str], None] = 'd4e1f9a2b613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_type', sa.String(length=32), nullable=False),
    sa.Column('segment_value', sa.String(length=64), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_range_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_factors_computed_at'), 'calibration_factors', ['computed_at'], unique=False)
    op.create_index(op.f('ix_calibration_factors_segment_type'), 'calibration_factors', ['segment_type'], unique=False)
    op.create_index(op.f('ix_calibration_factors_segment_value'), 'calibration_factors', ['segment_value'], unique=False)
    op.create_table('settled_bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('local_odds', sa.Float(), nullable=False),
    sa.Column('fair_probability', sa.Float(), nullable=False),
    sa.Column('edge_percentage', sa.Float(), nullable=False),
    sa.Column('suggested_stake', sa.Float(), nullable=False),
    sa.Column('model_source', sa.String(length=32), nullable=False),
    sa.Column('lineup_confirmed', sa.Boolean(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closing_sharp_odds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settled_bets_bookmaker_id'), 'settled_bets', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_settled_bets_match_id'), 'settled_bets', ['match_id'], unique=False)
    op.create_index(op.f('ix_settled_bets_settled_at'), 'settled_bets', ['settled_at'], unique=False)
    # batch mode: SQLite can't ALTER TABLE ADD COLUMN ... FOREIGN KEY or drop
    # constraints directly, same reasoning as d4e1f9a2b613's lineup_confirmed
    # migration - batch mode rebuilds the table instead.
    with op.batch_alter_table('value_bets') as batch_op:
        batch_op.add_column(sa.Column('bookmaker_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f('ix_value_bets_bookmaker_id'), ['bookmaker_id'], unique=False
        )
        batch_op.create_foreign_key(
            'fk_value_bets_bookmaker_id_bookmakers', 'bookmakers', ['bookmaker_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('value_bets') as batch_op:
        batch_op.drop_constraint('fk_value_bets_bookmaker_id_bookmakers', type_='foreignkey')
        batch_op.drop_index(op.f('ix_value_bets_bookmaker_id'))
        batch_op.drop_column('bookmaker_id')
    op.drop_index(op.f('ix_settled_bets_settled_at'), table_name='settled_bets')
    op.drop_index(op.f('ix_settled_bets_match_id'), table_name='settled_bets')
    op.drop_index(op.f('ix_settled_bets_bookmaker_id'), table_name='settled_bets')
    op.drop_table('settled_bets')
    op.drop_index(op.f('ix_calibration_factors_segment_value'), table_name='calibration_factors')
    op.drop_index(op.f('ix_calibration_factors_segment_type'), table_name='calibration_factors')
    op.drop_index(op.f('ix_calibration_factors_computed_at'), table_name='calibration_factors')
    op.drop_table('calibration_factors')
    # ### end Alembic commands ###
