"""create initial tables

Revision ID: f1457c4e1098
Revises: 
Create Date: 2026-06-30 20:45:31.496338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1457c4e1098'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_sharp', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_bookmakers_name')
    )
    op.create_table('leagues',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('home_team_id', sa.String(length=64), nullable=False),
    sa.Column('away_team_id', sa.String(length=64), nullable=False),
    sa.Column('league_id', sa.String(length=64), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_utc'), 'matches', ['kickoff_utc'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_table('team_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_forms_team_id'), 'team_forms', ['team_id'], unique=False)
    op.create_table('odds_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odds_value', sa.Float(), nullable=False),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_quotes_bookmaker_id'), 'odds_quotes', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_odds_quotes_match_id'), 'odds_quotes', ['match_id'], unique=False)
    op.create_index(op.f('ix_odds_quotes_quoted_at'), 'odds_quotes', ['quoted_at'], unique=False)
    op.create_table('value_bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('local_odds', sa.Float(), nullable=False),
    sa.Column('fair_probability', sa.Float(), nullable=False),
    sa.Column('edge_percentage', sa.Float(), nullable=False),
    sa.Column('suggested_stake', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_bets_match_id'), 'value_bets', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_bets_match_id'), table_name='value_bets')
    op.drop_table('value_bets')
    op.drop_index(op.f('ix_odds_quotes_quoted_at'), table_name='odds_quotes')
    op.drop_index(op.f('ix_odds_quotes_match_id'), table_name='odds_quotes')
    op.drop_index(op.f('ix_odds_quotes_bookmaker_id'), table_name='odds_quotes')
    op.drop_table('odds_quotes')
    op.drop_index(op.f('ix_team_forms_team_id'), table_name='team_forms')
    op.drop_table('team_forms')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_utc'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('leagues')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
